##
## EPITECH PROJECT, 2019
## CAESAR
## File description:
## Makefile
##

NAME	=	challenge09

SRC		=	challenge09.py

all:
	cp $(SRC) ../$(NAME)

clean:
	rm -f $(NAME)

fclean:	clean
	rm -f ../$(NAME)

re: fclean all

.PHONY: fclean all re clean